name: Build Native Version


on: 
  workflow_dispatch:
    inputs:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: mstksg/get-package@v1
        with:
          apt-get: libgmp-dev
      - uses: mstksg/setup-stack@v1
      
      # Tasks
      - run: nix-shell --run "just install-deps"
      - run: nix-shell --run "just build-prod"
      
  tauri:
    needs: build
    
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      
      # Dependencies
      - run: cargo install tauri-bundler --force
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
          
      # Tasks
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distPath: ./build
          iconPath: ./src/Static/Images/icon.png
          prerelease: true
          releaseDraft: true
        
    
