name: Build Native Version


on: 
  workflow_dispatch:
    inputs:


jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "just install-deps"
      - run: nix-shell --run "just build-prod"
      - run: ls ./build
